/**
 * Reversi API
 * API for Reversi game
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CellState from './CellState';
import Score from './Score';

/**
 * The BoardInfo model module.
 * @module model/BoardInfo
 * @version 1.0.0
 */
class BoardInfo {
    /**
     * Constructs a new <code>BoardInfo</code>.
     * @alias module:model/BoardInfo
     */
    constructor() { 
        
        BoardInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BoardInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BoardInfo} obj Optional instance to populate.
     * @return {module:model/BoardInfo} The populated <code>BoardInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BoardInfo();

            if (data.hasOwnProperty('board')) {
                obj['board'] = ApiClient.convertToType(data['board'], [[CellState]]);
            }
            if (data.hasOwnProperty('finished')) {
                obj['finished'] = ApiClient.convertToType(data['finished'], 'Boolean');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = Score.constructFromObject(data['score']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BoardInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BoardInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['board'])) {
            throw new Error("Expected the field `board` to be an array in the JSON data but got " + data['board']);
        }
        // validate the optional field `score`
        if (data['score']) { // data not null
          Score.validateJSON(data['score']);
        }

        return true;
    }


}



/**
 * @member {Array.<Array.<module:model/CellState>>} board
 */
BoardInfo.prototype['board'] = undefined;

/**
 * @member {Boolean} finished
 */
BoardInfo.prototype['finished'] = undefined;

/**
 * @member {module:model/Score} score
 */
BoardInfo.prototype['score'] = undefined;






export default BoardInfo;

