/**
 * Reversi API
 * API for Reversi game
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CellState.
* @enum {}
* @readonly
*/
export default class CellState {
    
        /**
         * value: "W"
         * @const
         */
        "W" = "W";

    
        /**
         * value: "B"
         * @const
         */
        "B" = "B";

    
        /**
         * value: "E"
         * @const
         */
        "E" = "E";

    

    /**
    * Returns a <code>CellState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CellState} The enum <code>CellState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

