/**
 * Reversi API
 * API for Reversi game
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CellState from './CellState';
import Opponent from './Opponent';

/**
 * The GameRequest model module.
 * @module model/GameRequest
 * @version 1.0.0
 */
class GameRequest {
    /**
     * Constructs a new <code>GameRequest</code>.
     * @alias module:model/GameRequest
     */
    constructor() { 
        
        GameRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameRequest} obj Optional instance to populate.
     * @return {module:model/GameRequest} The populated <code>GameRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameRequest();

            if (data.hasOwnProperty('board')) {
                obj['board'] = ApiClient.convertToType(data['board'], [[CellState]]);
            }
            if (data.hasOwnProperty('opponent')) {
                obj['opponent'] = Opponent.constructFromObject(data['opponent']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['board'])) {
            throw new Error("Expected the field `board` to be an array in the JSON data but got " + data['board']);
        }
        // validate the optional field `opponent`
        if (data['opponent']) { // data not null
          Opponent.validateJSON(data['opponent']);
        }

        return true;
    }


}



/**
 * @member {Array.<Array.<module:model/CellState>>} board
 */
GameRequest.prototype['board'] = undefined;

/**
 * @member {module:model/Opponent} opponent
 */
GameRequest.prototype['opponent'] = undefined;






export default GameRequest;

