/**
 * Reversi API
 * API for Reversi game
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "./ApiClient";
import GameRequest from './model/GameRequest';
import GameResponse from './model/GameResponse';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the makeOpponentMove operation.
     * @callback module:api/DefaultApi~makeOpponentMoveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GameResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Make the opponent's move
     * @param {module:model/GameRequest} gameRequest 
     * @param {module:api/DefaultApi~makeOpponentMoveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GameResponse}
     */
    makeOpponentMove(gameRequest, callback) {
      let postBody = gameRequest;
      // verify the required parameter 'gameRequest' is set
      if (gameRequest === undefined || gameRequest === null) {
        throw new Error("Missing the required parameter 'gameRequest' when calling makeOpponentMove");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GameResponse;
      return this.apiClient.callApi(
        '/api/game/move', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
