/**
 * Reversi API
 * API for Reversi game
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BoardInfo from './model/BoardInfo';
import CellState from './model/CellState';
import GameRequest from './model/GameRequest';
import GameResponse from './model/GameResponse';
import GameResponseNextMovesInner from './model/GameResponseNextMovesInner';
import Move from './model/Move';
import Player from './model/Player';
import Score from './model/Score';
import DefaultApi from './api/DefaultApi';


/**
* API for Reversi game.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ReversiApi = require('index'); // See note below*.
* var xxxSvc = new ReversiApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ReversiApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ReversiApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ReversiApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BoardInfo model constructor.
     * @property {module:model/BoardInfo}
     */
    BoardInfo,

    /**
     * The CellState model constructor.
     * @property {module:model/CellState}
     */
    CellState,

    /**
     * The GameRequest model constructor.
     * @property {module:model/GameRequest}
     */
    GameRequest,

    /**
     * The GameResponse model constructor.
     * @property {module:model/GameResponse}
     */
    GameResponse,

    /**
     * The GameResponseNextMovesInner model constructor.
     * @property {module:model/GameResponseNextMovesInner}
     */
    GameResponseNextMovesInner,

    /**
     * The Move model constructor.
     * @property {module:model/Move}
     */
    Move,

    /**
     * The Player model constructor.
     * @property {module:model/Player}
     */
    Player,

    /**
     * The Score model constructor.
     * @property {module:model/Score}
     */
    Score,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
