/**
 * Reversi API
 * API for Reversi game
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BoardInfo from './BoardInfo';
import Move from './Move';

/**
 * The GameResponseNextMovesInner model module.
 * @module model/GameResponseNextMovesInner
 * @version 1.0.0
 */
class GameResponseNextMovesInner {
    /**
     * Constructs a new <code>GameResponseNextMovesInner</code>.
     * @alias module:model/GameResponseNextMovesInner
     */
    constructor() { 
        
        GameResponseNextMovesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameResponseNextMovesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameResponseNextMovesInner} obj Optional instance to populate.
     * @return {module:model/GameResponseNextMovesInner} The populated <code>GameResponseNextMovesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameResponseNextMovesInner();

            if (data.hasOwnProperty('move')) {
                obj['move'] = Move.constructFromObject(data['move']);
            }
            if (data.hasOwnProperty('boardInfo')) {
                obj['boardInfo'] = BoardInfo.constructFromObject(data['boardInfo']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameResponseNextMovesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameResponseNextMovesInner</code>.
     */
    static validateJSON(data) {
        // validate the optional field `move`
        if (data['move']) { // data not null
          Move.validateJSON(data['move']);
        }
        // validate the optional field `boardInfo`
        if (data['boardInfo']) { // data not null
          BoardInfo.validateJSON(data['boardInfo']);
        }

        return true;
    }


}



/**
 * @member {module:model/Move} move
 */
GameResponseNextMovesInner.prototype['move'] = undefined;

/**
 * @member {module:model/BoardInfo} boardInfo
 */
GameResponseNextMovesInner.prototype['boardInfo'] = undefined;






export default GameResponseNextMovesInner;

