/**
 * Reversi API
 * API for Reversi game
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Score model module.
 * @module model/Score
 * @version 1.0.0
 */
class Score {
    /**
     * Constructs a new <code>Score</code>.
     * @alias module:model/Score
     */
    constructor() { 
        
        Score.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Score</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Score} obj Optional instance to populate.
     * @return {module:model/Score} The populated <code>Score</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Score();

            if (data.hasOwnProperty('black')) {
                obj['black'] = ApiClient.convertToType(data['black'], 'Number');
            }
            if (data.hasOwnProperty('white')) {
                obj['white'] = ApiClient.convertToType(data['white'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Score</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Score</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} black
 */
Score.prototype['black'] = undefined;

/**
 * @member {Number} white
 */
Score.prototype['white'] = undefined;






export default Score;

