/**
 * Reversi API
 * API for Reversi game
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ReversiApi);
  }
}(this, function(expect, ReversiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ReversiApi.Move();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Move', function() {
    it('should create an instance of Move', function() {
      // uncomment below and update the code to test Move
      //var instance = new ReversiApi.Move();
      //expect(instance).to.be.a(ReversiApi.Move);
    });

    it('should have the property row (base name: "row")', function() {
      // uncomment below and update the code to test the property row
      //var instance = new ReversiApi.Move();
      //expect(instance).to.be();
    });

    it('should have the property col (base name: "col")', function() {
      // uncomment below and update the code to test the property col
      //var instance = new ReversiApi.Move();
      //expect(instance).to.be();
    });

    it('should have the property player (base name: "player")', function() {
      // uncomment below and update the code to test the property player
      //var instance = new ReversiApi.Move();
      //expect(instance).to.be();
    });

  });

}));
